### ISSUE TITLE
inline thread_id() does not play with multiple compilation units (GCC 4.9)

### ISSUE THREAD

**Issue by craigminihan** [inkooboo/thread-pool-cpp#1]
The decl of thread_id as `inline static` causes issues with multiple compilation units under GCC 4.9, for example:

In the test directory create a new file `getWorkerIdForCurrentThread.cpp`:
```c++
#include <worker.hpp>
size_t getWorkerIdForCurrentThread() { return *thread_id(); }
size_t getWorkerIdForCurrentThread2() { return Worker::getWorkerIdForCurrentThread(); }
```

Declare the new functions at the top of `thread_pool.t.cpp`:
```c++
size_t getWorkerIdForCurrentThread();
size_t getWorkerIdForCurrentThread2();
```

Update `doTest("post job")`, add the following line in the lambda after `std::packaged_task<int()> ....`:
```c++
printf("\nThread id(1): %lu, id(2): %lu, id(3): %lu, id(4): %lu\n", 
  Worker::getWorkerIdForCurrentThread(), *thread_id(), 
  getWorkerIdForCurrentThread(), getWorkerIdForCurrentThread2());
```

Build and run `thread_pool.t.cpp` as usual, the output will show the new line:
```text
Thread id(1): 7, id(2): 7, id(3): 4294967295, id(4): 7
```
Compile with -O3 and we get even worse output (due to aggressive inlining):
```text
Thread id(1): 7, id(2): 7, id(3): 4294967295, id(4): 4294967295
```

In essence `getWorkerIdForCurrentThread.cpp` contains another instance of `tss_id` per thread since it was inlined by GCC and is never initialized to a valid value by the thread pool. Now when we call these functions we always see `-1ul` regardless of the thread we call from.

This limits the usefulness of the thread pool - at best you have to be extremely careful what you call and where when you have multiple CPPs.

**Comment by inkooboo** [comment]
Thanks, Craig. I tried to keep all code header-only, that is the reason of inline static. I'll look how to fix this issue,  but now I think you can do simple workaround by moving 'thread_id()' implementation to .cpp file.

**Comment by craigminihan** [comment]
@inkooboo I like the cleanness of your header approach - you have made some nice code here. I wasn't viewing the issue as a defect more of a warning to the wary - it took me a good few hours to figure out why the ids were going nuts. ;)

**Comment by inkooboo** [comment]
**Fixed** https://github.com/inkooboo/thread-pool-cpp/commit/75c1ad5cec88711ed192f528c97d58fb539df941
It was my error. It is incorrect to use 'static inline' in this case. Just 'inline' works fine. [Read more](http://stackoverflow.com/questions/10876930/should-one-never-use-static-inline-function)
