### ISSUE TITLE
Duplicate thread_pool directory?

### ISSUE THREAD

**Issue by emmenlau** [inkooboo/thread-pool-cpp#11]
There is `include/thread_pool` and `thread_pool` directory with similar files, but different
version of the files. Is one of the two deprecated?

**Comment by SuperV1234** [comment]
I think that the `thread_pool` directory was committed accidentally. I removed it in 16b9bdcf10611586d4298c7bdde7809b09dd84b7. @inkooboo feel free to revert in case I missed something.

**Comment by inkooboo** [comment]
Yep, sorry. Thank you for fixing this.

**Comment by emmenlau** [comment]
Thanks a lot! Nice work!
