### ISSUE TITLE
Thread start/end lambdas

### ISSUE THREAD

**Issue by craigminihan** [inkooboo/thread-pool-cpp#14]
I have a use-case where I need to invoke code on each of the worker threads on thread creation and shutdown.

I have already written the code in my fork and would like to PR it here if you want the feature.

The use case is for running Mozilla's SpiderMonkey JavaScript engine in the thread pool. SpiderMonkey uses TLS so the engine must run on the thread that created it.

The new signature for `threadFunc` looks like:

```c++
inline void Worker::threadFunc(size_t id, Worker *steal_donor, OnStart onStart, OnStop onStop)
```

In addition each `handler()` takes the thread 'id' as the first param, this allows the handler to locate the correct engine, eg:

```c++
void myHandler(size_t id) {
    auto& engine = engines[id];
    engine.Evaluate("(function() { return 42; })()"); // run some JS
}
```

My change is based on an old commit on your master. I've raised this as an issue now since it will take me some time to merge it and I'd rather not bother if you don't want it.

**Comment by inkooboo** [comment]
I don't think it is good idea to add this into this particular code base. I believe your use-case is quite unique and it is easier and more correct to implement your own thread pool. Also I don't like idea of managing task scheduling/distribution or thread ids access outside. It breaks abstraction.
