### ISSUE TITLE
Difference between packaged task and fixed function

### ISSUE THREAD

**Issue by agauniyal** [inkooboo/thread-pool-cpp#15]
Hi, I couldn't find any documentation related to the project so I looked into tests and found 2 different ways to send tasks to thread pool if I'm guessing right. So what's the difference b/w using fixed function vs using packaged task here?

**Comment by inkooboo** [comment]
Hi, basically the `std::packaged_task` gives `std::future` so you can wait for execution completion on it, so you know when you code will be executed and can wait for its result. Using `std::packaged_task` it is possible to implement sort of synchronous execution in thread pool threads.
