### ISSUE TITLE
change the implementation of thread_pool_options to a .cpp file

### ISSUE THREAD

**Issue by MatthewButterfly** [inkooboo/thread-pool-cpp#16]
I need to use the ThreadPoolOptions to set the thread count and the queue size. Since the ThreadPool's ctor only accepts the ThreadPoolOptions, I met an "multiple definition of" error when linking in my program.
May you remove the implementation of ThreadPoolOptions to antoher .cpp file or add a ctor in ThreadPool to control the queue size and thread count?

**Comment by inkooboo** [comment]
Might it be that you are using old version of code? Current version has separate files for `ThreadPool` and `ThreadPoolOptions`.

**Comment by MatthewButterfly** [comment]
Thanks for your quick response.
In order to make sure that I have the right version, attached the commits as below. 
The latest commit for the project is 884eb74  on Jun 3, and the latest commit for thread_pool_options.hpp is 71d74ec  on May 21.  Please tell me that is not right.

In the version which is commit on May 21, the implementation of ThreadPoolOptions is still in the same file with the declaration. 
I mean that separate the implementation of ThreadPoolOptions and the declaration of the ThreadPoolOptions into two files. 
I noticed that the class ThreadPoolOptions is not a template class. I can pass the compile after move the implementation to another file.
Thanks for your library, I can't image I can develop a concurrency programming such easy without this library.

**Comment by ilyapopov** [comment]
It should be enough to mark all the member functions `inline`.

**Comment by inkooboo** [comment]
Fixed
