### ISSUE TITLE
Task may drop when thread pool destruct

### ISSUE THREAD

**Issue by machunleilei** [inkooboo/thread-pool-cpp#17]
thread pool call worker's stop method when destruct and set worker's runing flag to false
worker's thread proc exit when runing flag is set to false,  ignore weather more tasks in its task queue

can worker wait all tasks finish when thread pool destruct

**Comment by inkooboo** [comment]
Yes, it will drop queued jobs. I don't see clear way to introduce optional feature of draining job queue before exit. Also it looks for me as bad idea. If I told to stop I stop.

**Comment by yvoinov** [comment]
Agreed. Pool should immediately stops, whenever queue empty or not.
