### ISSUE TITLE
Idling Performance

### ISSUE THREAD

**Issue by SeverTopan** [inkooboo/thread-pool-cpp#20]
I wanted to share some results relating to the performance of this thread pool when all member threads are idle. These results are caused by the waiting loop in threads that are idle.

![thread-pool-cpp_idle_gcc](https://user-images.githubusercontent.com/17536615/35520202-61b45828-04e4-11e8-8772-09ef0c326355.png)
![thread-pool-cpp_idle_msvc](https://user-images.githubusercontent.com/17536615/35520203-62240042-04e4-11e8-972b-6914097cbcae.png)

Though its probably not a great idea to run 500 threads on a machine with 8 logical cores, a large number of threads can be needed for blocking i/o operations, and the idle CPU usage overhead can burden and drain the battery life of client applications.

**Comment by yvoinov** [comment]
Pool is not like to be idle, yes. Job stealing works ever when idle. I guess sleep implementation will be a bit complex and gives some addition latency when will require to wake up pool.

I've noticed this effect. But in my own case it is low, and seems bad idea to create 500 threads per pool for only 8 hardware cores ;).

**Comment by SeverTopan** [comment]
@yvoinov I agree that 500 threads is excessive on a machine with 8 cores. The reason I pushed it that far was to test the limits on my machine in the context of this thread pool, and to extrapolate the results of the idling performance.

The point of this issue is that this thread pool consumes CPU even when idle. Whether or not this is a problem is completely dependent on your use case.

In my particular use case, I want extra threads lying around in my thread pool. This drives up the number of threads that may be idling at the same time. Reasons to keep some extra threads around are:
* If my use cases requires blocking at higher levels, I need enough threads in my thread pool to ensure that I don't end up in a deadlock situation. 
* If my use case requires multiple concurrent i/o operations on the thread pool, this is another situation where I need to keep extra threads around in my pool.

Let's say we take the lowest data point on the Linux VM with 4 cores (which is 50 threads). Is 3% CPU usage an acceptable level of consumption? Some cases where this might not be ideal:
* A system with other processes that contend for CPU resources.
* A system that runs on battery. The CPU usage when idle will drain this.
* Non-batch applications, where in general idle background tasks should minimize resource consumption.

**Comment by yvoinov** [comment]
In my case, I've started 64k threads on server (bare metal SPARC) with 8 cores and 32 Gb RAM :) All memory + swap was eaten in minutes, just with idle threads and proportional queue.

I still think it is bad idea to run more threads than physical/logical cores.

Yes, I see ~3% idle cpu usage with empty thread pool. Yes, I think this is acceptable.
No, I don't care about laptop battery because of using thread pool only on servers.
This idle consumption is continue pool benefits - I see no way to implement job stealing with sleeping workers.

If battery/laptop applications is critical for you - may be better to consider yet another thread pool implementation, without job stealing/load balancing.

**Comment by inkooboo** [comment]
@SeverTopan I think you misuse thread pool pattern. It is not supposed to handle real-time-like I/O, there exist non-blocking async API at the OS level for this. There is *NO* point of having more threads in thread pool then logical cores number.

**Comment by stewartbright** [comment]
@yvoinov, @inkooboo, I think you are making a lot of assumptions about what someone might want to use a thread pool for when you say there is no point in having more threads than logical cores. If all the code you are executing in the thread pool is pure computation, and never sleeps/waits/blocks (synchronization, signals, I/O, etc), then I agree with you.

Purely from the perspective of maximizing CPU utilization, there is no harm or observable overhead in having the number of threads be 2-3x the number of cores, and it can help boost utilization when the work being done is not pure computation.
