### ISSUE TITLE
Explain getWorker

### ISSUE THREAD

**Issue by MBkkt** [inkooboo/thread-pool-cpp#36]
Hi, please explain why this is so?  https://github.com/inkooboo/thread-pool-cpp/blob/master/include/thread_pool/thread_pool.hpp#L149 
It seems a fairly frequent use case is pushing from one thread of a bunch of tasks. 
I understand the idea of ​​locality, but at first glance it doesn't seem to work? After all, if we push a task from the thread of the thread pool, this does not necessarily mean that its number is equal to its number in the array

Maybe something like this would be work better?
```
getWorker:
auto idx = current thread id;
if last_idx == idx {
     return last_worker;
}
for (worker : workers) {
     if (idx == worker.idx) {
         last_idx = idx;
         last_worker = worker;
         return worker;
     }
}
Logic with m_next_worker
```
Or something like this
```
thread_local worker_index{-1}; // set in worker::start
if (worker_index != -1) {
     return workers[worker_index];
}
Logic with m_next_worker
```

**Comment by inkooboo** [comment]
Hi, I'm not sure I understand the issue, original design idea was that for jobs that are posted from threads **outside** of thread pool we use **round robin** task distribution. And jobs from **inside** thread pool are queued on exactly **same thread**.
For your code examples it looks like current implementation is exactly your second algorithm:
* set `worker_index` to `-1` by default for "external" threads: https://github.com/inkooboo/thread-pool-cpp/blob/master/include/thread_pool/worker.hpp#L90
* assign `worker_index` for current thread in thread pool: https://github.com/inkooboo/thread-pool-cpp/blob/master/include/thread_pool/worker.hpp#L155
* re-use same worker if `worker_index` assigned: https://github.com/inkooboo/thread-pool-cpp/blob/master/include/thread_pool/thread_pool.hpp#L159

**Comment by MBkkt** [comment]
Yes you are right, I read something bad, for some reason it seemed as if getCurrentIdThread calls std::this_thread::get_id()
