### ISSUE TITLE
can't compile with vc2015

### ISSUE THREAD

**Issue by qicosmos** [inkooboo/thread-pool-cpp#6]
static thread_local size_t tss_id = -1u;
the code will cause an error C4146.

**Comment by inkooboo** [comment]
As far as I understand  C4146 is not error but just MSVC specific warning. Possibly it is not even good idea to treat warnings as errors using MSVC compiler. I'm not sure if you are able compile any of big open source project with this option. Finally it is up to you fix it. You can initialize it any way that works for your environment.

**Comment by qicosmos** [comment]
@inkooboo hi, i konw this is the warning of the vc2015.
the  tss_id could be initialized by 0?

**Comment by inkooboo** [comment]
No, 0 is not good. The idea is to give 'tss_id' the reasonable big value. '-1u' actually means: Give me maximum possible unsigned int.

**Comment by qicosmos** [comment]
maybe std::numeric_limits<int>::max() is better than -1.

**Comment by inkooboo** [comment]
Yes it should be good. You are welcome to create pull request with this fix if you want.
