### ISSUE TITLE
The thread pool can't drain

### ISSUE THREAD

**Issue by qicosmos** [inkooboo/thread-pool-cpp#7]
I wan't drain all the task, but can't find the method, could you add the drain method?

**Comment by qicosmos** [comment]
btw, add a method which is used to get task number of the pool.

**Comment by inkooboo** [comment]
I'm afraid it is not possible to implement these 2 features in this thread pool. Here we pay for high performance with lack of control over execution process. If you need more control, you probably need another thread pool implementation.
